### PR TITLE
Modal and Rating

### PR DESCRIPTION
**Pull request by amantulsyan35**
Add:
1. Modal
2. Rating

### CODE REVIEW

**Review by sri-rishi — COMMENTED** [review]
On clicking it's not showing modal and button click me spelling is no correct

**Review by sri-rishi — CHANGES_REQUESTED** [review]
use cursor: pointer for buttons

**Review by shangkaul — APPROVED** [review]
Looks good to merge!

**Tip:** You can add active/inactive stars to the rating component.

**Comment by Sahil25061999** [comment]
looks good can be merged.

**Pull request merged**
